[env]
TERM= "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations="none"

[font]
normal.family ="UbuntuMono Nerd Font"
size = 16

[general]
#themes
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
